### ISSUE TITLE
add token authentication

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#145]
instead of relying on Basic authentication only (and forcing scripts to keep the login/password of the users), can we add a column token in the users, min 32 char long or whatever you deem appropriate and accepts it if the header contains

Authorization: Bearer $USER_TOKEN

ideally, each user is giving a token already, but right now, we can update the db by hand

and probably some script only users would only work with token in the future

**Comment by marcinkoziej** [comment]
done
