### ISSUE TITLE
why v2 vs v1 messages?

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#186]
Hi,

Should we care about v1 messages or they have been 100% obsoleted with v2?

ie. do we need to keep both or could we have proca-queue versioning and skip a major version version when changing message format?

rationale: if you put a version number, the user is going to wonder if they need to handle both versions, whats'  the changes... all this mental workload could be avoided by only exporting ActionMessage and EventMessage and let the package versioning as the indicator a breaking change on the format is introduced

**Comment by marcinkoziej** [comment]
only collect platform is using them, we should not care about them for any new dev, soon we will be able to remove support for it completely. (collect must still be updated)

**Comment by marcinkoziej** [comment]
>    rationale: if you put a version number, the user is going to wonder if they need to handle both versions, whats' the changes... all this mental workload could be avoided by only exporting ActionMessage and EventMessage and let the package versioning as the indicator a breaking change on the format is introduced

not sure where you got this idea.
When I see MailJet APIv2 and APIv3 - i know i can choose to use the one i want and that's end of my problem.

**Comment by tttp** [comment]
exactly, you can choose one of the other, but it means you need to investigate what's the difference between them and it's an extra "task" that we put for no reason on our users.

I'll offer you for chrismas [don't make me think](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think), I found it super useful for UX design, it might help sync us better

and agree on the package versioning, we should improve indeed ;)
