### ISSUE TITLE
add a status to campaign

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#190]
In order to handle better closing campaign, it would be great to have a status with:

- live
- closed (paused?)

I'm not super keen on having a hard closing (I'm sure it would screw some campaigns that badly planned), but what about we have a "soft" closing, ie we store the actions with the testing=true?

we could "unblock" them later (by setting testing=false), but at least the counter wouldn't be increased but without data loss/hard rejection

**Comment by marcinkoziej** [comment]
For me this is "unspecific" feature.

We had action page live status - i had  to remove it. It was unused / badly used / mainly caused confusion.

Now the feature description says we want a closed status, but then in next sentence you say actually we don't want it _for real_

I say: YAGNI to this.

**Comment by tttp** [comment]
right, let's clarify with the demand from the campaign coordinator: they want to be able to "freeze" the counter so they can communicate on the total number of signatures. Ain't YAGNI, they need it for PR and comm.

either we do a hard close and not accept new signatures after the end, or a soft close and accept but not count (like for the test mode)

Both these options would work, I have a small preference for the second one, but open if you prefer the first one
