### ISSUE TITLE
store IP address when collecting double opt-in consent

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#202]
Hi,

this is an initial discussion about the privacy/legal concerns of storing IP addresses

the legal rationale is that it makes it easier to defend in a data privacy case.

I'm not sure I understand the rationale here, say that Hans Schmitt sues the organisation because he says he never consented

with double opt-in, we can prove that someone that had access to Han's email opted-in.

Presumably, the only case where the IP address would be useful is if Hans says that wasn't him that clicked/he got his mailbox hacked

In that case, shouldn't it be the email provider the right person to track the IP address and show who (which IP address) accessed the mailbox?

So I'm not sure storing the IP address is the right solution here, but if we were, what would be the legal requirement? changing the DPA? asking the organisations using proca to change their privacy policy? should we add a mention on the double opt-in email that "your IP address will be stored if you click on the email?"

Lots of questions ;)

**Comment by marcinkoziej** [comment]
I would add this to `supporters` model as `email_status_changed_ip` or similar name, next to:

```
    field :email_status, EmailStatus, default: :none
    field :email_status_changed, :utc_datetime
```
`email_status_changed` is changed to `double_opt_in`

**Comment by marcinkoziej** [comment]
Maybe GDPR allows storing IP for legal enforcement without user consent.

**Comment by tttp** [comment]
gpde is not requiring it anymore
