### ISSUE TITLE
Allow test emails to be sent to the email put in the form

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#203]
When conducting tests (proca_test get param), the mail2target actions don't send the emails to the real targets but to a test fixed test email. It makes it hard to validate the emails for the campaigner and creates confusion

The ideal scenario is that the campaigner puts their own email address as the supporter (jane@example.org) and she receives the thank you email (if set up) AND the email that was supposed to be sent to the target

to make it clearer that the second email is a test and isn't meant to be the one they receive normally, we should add a "[TEST]" at the start of the subject line.

the test emails aren't following the "normal" drip delivery configurations and are sent as soon as possible

**Comment by tttp** [comment]
replaced by  #175

**Comment by 1v4n4** [comment]
This one seems partially implemented - test emails sometimes go to the test email address, and sometimes to the address inputted in the form. We do not know how is that decided.
The goal: test emails always go to the address entered on the form.

**Comment by destag** [comment]
From what I found in the code:

Test email is sent only when mtt has `test_email` set:
https://github.com/fixthestatusquo/proca-server/blob/c041809a90f281e6fdce908d1687f648e5c7e768/proca/lib/proca/server/mtt_worker.ex#L78-L79

But then, when we send emails it checks if supporter is set for this campaign, and returns test_email otherwise:
https://github.com/fixthestatusquo/proca-server/blob/c041809a90f281e6fdce908d1687f648e5c7e768/proca/lib/proca/server/mtt_worker.ex#L297-L302

@1v4n4 Is it possible that the test message that were sent to test_email were related to actions that had no supporter assigned?

**Comment by 1v4n4** [comment]
Here's how it seems to be working now 
1. if a default email address is not set on a campaign level,  no test emails are sent
2. if a default email address is set 
    -  supporter email if the supporter is known to our auth (for if ever tried to log in to dashboard) 
    -  to a test email address if the supporter is unknown

when you set the test address, you'll receive test emails from the period when there was no email address set

(hard to test because test emails are not instant, but not as late as before)

**Comment by 1v4n4** [comment]
It looks like the problems we had were mainly because we didn't know how to configure this and test emails not arriving in a reasonable time. 
It could be working as it is.

@tttp should we improve this or document it and go to https://github.com/fixthestatusquo/proca-server/issues/175?

**Comment by tttp** [comment]
Hi,

we should either always put a test_email (defaulting to the one creating the org) or remove that test. 

I do not get the logic of testing if that email exists in the first place, probably a left over from previous versions when it was only sent to the test_email, so probably easier to simply remove that test

for the "send only to known emails": I think it was to prevent abuses and so people wouldn't use it to spam. I think the solution that was adopted to put a clear "it's a test" kind of message is enough for now, what do you think?

one option would be to cc the test_email and always send to the email put on the form (rationale, so the responsible person of the org can see what's happening)

@destag could you check if it's simple?

1) when creating an org, always put the email of the user that created that org
2) always send the test email to the email put in the form, even if no test_email is set
3) cc (or bcc?) the test_email if test_email is set

X+
P.S. @1v4n4 and then we can change our workflow to put the widgets in test mode first and guide the campaigner to take an action on proca-admin

**Comment by tttp** [comment]
> It looks like the problems we had were mainly because we didn't know how to configure this and test emails not arriving in a reasonable time.
> It could be working as it is.

we shouldn't have to configure anything to get the test mode working, it should work out of the box without needing non obvious changes ;)

and we have and will still have confused users that will put different emails than those that we know (and it's useful to allow them to test on various webmail anyway, it's good they try multiple times on gmail, hotmail...)

**Comment by destag** [comment]
> 1. when creating an org, always put the email of the user that created that org

@tttp So should we add some `default_email` to org schema or assign current user as some kind of `default_contact`? AFAIK right now Org is not associated with any email

**Comment by tttp** [comment]
aah, you are right, we should take the email of the user that created the campaign, not the one from the org coordinating it
