### ISSUE TITLE
install a local dev version

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#205]
Hi @marcinkoziej 

@hassanRsiddiqi is trying to install locally a dev version of proca-server to tackle some of the tasks you've identified

based on my install this weekend, I've updated the README with asdf

we're logging here where we get stuck/various issues

### elixir version
I've installed (and put on .tool-options)
erlang 24.3.3
elixir 1.14.4
however, elixir 1.7 is defined in mix.exs. should it be changed?

### utils/configure-development-env.sh
this seems to setup database + rabbitmq

it's not clear for me how/if

- seed the dev database (with an org+user+campaign+actionpage?)
- configure the .env needed to run proca server (our /etc/proca/xxx on ansible)

### minimal dev mode
would it make sense to handle running without rabbitMQ? I'd assume most of the dev can be done without it, would it be difficult to disable the features that rely on it if AMQP_URL is disabled?

### gotrue 
looking at the env file, there are a bunch of JWT variables, are they required or can it work with basic auth in a dev context?

**Comment by marcinkoziej** [comment]
- server can run without rabbitmq, but will not process actions then. Server checks the availability of RabbitMQ periodically.

- Supported auth modes are:
  - http basic (browse to / to register)
  - jwt symmetrical and asymmetrical

- use `mix ecto.setup`. Knowledge of [Ecto](https://hexdocs.pm/ecto/getting-started.html) docs is absolutely mandatory

- dev has default configuration in `config/dev.exs` - this is standard [Phoenix Framework](https://hexdocs.pm/phoenix/overview.html), which knowledge is absolutely mandatory.

**Comment by hassanRsiddiqi** [comment]
@marcinkoziej this is what I see over there, am I missing some configuration?
<img width="1422" alt="Screen Shot 2023-04-30 at 11 12 30 PM" src="https://user-images.githubusercontent.com/23057904/235374227-aaf52410-6bf5-4153-a753-43c261d177e6.png">

**Comment by hassanRsiddiqi** [comment]
I did all of these ' setups: ["deps.get", "ecto.setup", "cmd --cd assets npm install"]` DB is set up and the project is working locally, but I don't see any action.

**Comment by marcinkoziej** [comment]
You might be missing a call to `mix phx.digest`?
It seems to work - but it's missing some assets. can you check in web dev what files are missing?

**Comment by marcinkoziej** [comment]
@hassanRsiddiqi did it work?

**Comment by tttp** [comment]
@hassanRsiddiqi told me he still have issues running it.

one issue was to get a super admin user working to be able to config the server further (eg add orgs, campaign, actionpage...), 

is there a command to make it easy to add one?

**Comment by hassanRsiddiqi** [comment]
I am using the username and password from the terminal window, which I got it after seeds. this show me.
```
Thanks! Fetching campaign list to check the credentials
Nope, something is not ok with your sign-in:  [GraphQL] Can not authenticate with these Basic HTTP credentials
```

**Comment by hassanRsiddiqi** [comment]
I have the rabbitMQ process running on my terminal, and I am using the correct credentials, maybe I am missing something extra in RabbitMQ? I followed the [this](https://github.com/fixthestatusquo/proca-server/tree/main/proca) notes, and I am not using docker.

**Comment by marcinkoziej** [comment]
> I am using the username and password from the terminal window, which I got it after seeds. this show me.

did you add the local server to use with the cli ? it might try to connect to api.proca.app

**Comment by marcinkoziej** [comment]
Can you sign in using the browser at http://localhost:4000 ?

**Comment by hassanRsiddiqi** [comment]
yes, I can signIn at localhost, using the same credetials.

**Comment by hassanRsiddiqi** [comment]
> > I am using the username and password from the terminal window, which I got it after seeds. this show me.
> 
> did you add the local server to use with the cli ? it might try to connect to api.proca.app

Where to do these changes, in npm proca? the agent?

**Comment by tttp** [comment]
> I am using the username and password from the terminal window, which I got it after seeds. this show me.
> 
> ```
> Thanks! Fetching campaign list to check the credentials
> Nope, something is not ok with your sign-in:  [GraphQL] Can not authenticate with these Basic HTTP credentials
> ```

Which command are you running?

**Comment by hassanRsiddiqi** [comment]
> > I am using the username and password from the terminal window, which I got it after seeds. this show me.
> > ```
> > Thanks! Fetching campaign list to check the credentials
> > Nope, something is not ok with your sign-in:  [GraphQL] Can not authenticate with these Basic HTTP credentials
> > ```
> 
> Which command are you running?

<img width="857" alt="Screen Shot 2023-05-22 at 8 01 05 PM" src="https://github.com/fixthestatusquo/proca-server/assets/23057904/a6c0c629-854d-4c79-a3f0-3ccb1f3a355f">

**Comment by tttp** [comment]
when I'm asking which command you are running, I'm asking you the command you ran, not a screenshot of the result ;)

what is the command you're running?
