### ISSUE TITLE
bunch of "superadmin" commands

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#206]
Hi @marcinkoziej,

on root/scripts, we have a bunch of superadmin commands (make-owner, list-orgs...) is there any cons to add them to this repository?

**Comment by marcinkoziej** [comment]
no, just double check if there are no passwords there (there should not)

they use an RPC mechanism to run code on local server using a token in `RELEASE_COOKIE="$RELEASE_ROOT/releases/COOKIE`, using /usr/bin/proca-live script.
