### ISSUE TITLE
error in documentation?

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#215]
Hi @marcinkoziej 

going through the documentation, it's a good moment to look back at what has been achieved and admire the design, quite an enjoyable summer activity, congratulations!

this page went in, it's mostly empty, is this a mistake?

https://github.com/fixthestatusquo/proca-server/blob/main/proca/guides/Proca.Users.Status.html

**Comment by marcinkoziej** [comment]
> going through the documentation, it's a good moment to look back at what has been achieved and admire the design, quite an enjoyable summer activity, congratulations!

Is this referring to whole KB? unsure if I follow.

Yes this file is there by some mistake (probably i hit file save for no reason there).
File with same name is here:  https://docs.proca.app/Proca.Users.Status.html
