### ISSUE TITLE
documenting the admin permissions

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#216]
most of the permissions/roles are linked to an organisation (staffer), but there were a bunch that were set at the instance level, didn't it?

I didn't find the documentation about what they are/what they allow, could you help clarify @marcinkoziej ?

What I'm looking for (and not sure if it's there/not yet or done differently):

- add a global "can read everything but PII" role
this would be used by a server/micro-service to allow it to fetch the detail of each organisation/campaign/widget, but can't get access to PII
- add a global "can read and write and create everything but PII" role
this would be used by a support staff (or may be a micro-service), to allow them to modify campaigns/widgets, but can't get acess to PII

something else? I remember something was done, but can't find the details of what it was

**Comment by marcinkoziej** [comment]
I've updated the permissions page for `Proca.Permission` (in git)

I cannot `sync-docs` anymore so you need to sync the docs.proca.app

These flags can be added in `Proca.Permission` and then checked for in API

**Comment by tttp** [comment]
> I cannot sync-docs anymore so you need to sync the docs.proca.app

My apologies, I might have disabled something on trying to migrate.

how does sync-docs work?

**Comment by marcinkoziej** [comment]
just see the script :)
