### ISSUE TITLE
send a different email to duplicate signatories

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#220]
the aim is to be able to send a different email than the regular thank you one if the email address has already signed.

for performance and workflow reason, add the dupe_rank as a variable sent to the thank you email template might not be possible

a potential workaround is to have a different template/email and send it to a separate "duplicate" queue, so it would send the regular thank you email and a "error" email after

this is not as good as adding dupe_rank to the thank you email, but might do the trick

**Comment by marcinkoziej** [comment]
There is an `{{isDupe}}` variable given to email template.

**Comment by marcinkoziej** [comment]
updated the doc about this `EmailMerge` module

**Comment by tttp** [comment]
https://github.com/fixthestatusquo/proca-server/commit/40f8645b28794d1af8677ee725d75994ac0c2398
