### ISSUE TITLE
add dupe_rank to the message schema

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#222]
Hi @marcinkoziej,

is this correct that emails (eg thank you email) have a isDupe variable but this variable (or the underlying dupe_rank) isn't sent to the deliver queue?

https://github.com/fixthestatusquo/proca-server/blob/main/sdk/queue/src/actionMessage.ts#L106

is this "only" a matter or adding it to the schema and assign it or is this more complex?

**Comment by marcinkoziej** [comment]
Email template get `isDupe` because mustache does not have `if dupeRank > 0` construct. It only has `if truth` so `isDupe` is convenient.
The action queue message has `dupeRank` under `contact` - and it is indeed missing from TS declaration.

**Comment by marcinkoziej** [comment]
visible here:

![Screenshot from 2023-08-10 12-10-01](https://github.com/fixthestatusquo/proca-server/assets/156725/af95a660-511e-474a-8234-ba655ad5d497)
