### ISSUE TITLE
do not change campaign config keys when pushing campaigns to WEBHOOK

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#229]
The keys of campaign.config are modified when saving from webhook->n8n.
Unwanted modifications:
- snake case becomes camel case
- capital letters to lowercase
- this is what happens with URLs:
![Screenshot from 2024-05-14 19-52-06](https://github.com/fixthestatusquo/proca-server/assets/65791349/4e9db0b9-bbca-43b6-846c-36f8c2124260)
- any other we haven't noticed so far

this is a problem as the configuration as saved (or sent) is different than the one saved on the server.

Keys should not be modified!

the places that seem to camel case the keys:

https://github.com/fixthestatusquo/proca-server/blob/8e6aad0fddb2c50878420782f5d82709ca34d6c8/proca/lib/proca/stage/event.ex#L19

https://github.com/fixthestatusquo/proca-server/blob/8e6aad0fddb2c50878420782f5d82709ca34d6c8/proca/lib/proca/stage/event.ex#L61

**Comment by destag** [comment]
`camel_case_keys()` uses [ProperCase](https://github.com/johnnyji/proper_case) library which uses `Macro.camelize` under the hood, which in turn, as the official documentation says "Do not use it as a general mechanism for camelizing strings [...]" is not intended for general use.

I found two possible alternatives to `ProperCase` library:
https://github.com/nurugger07/inflex
https://github.com/wemake-services/recase

Another solution would be to check in `camel_case_keys` if key is a valid url and then skip camelize.

**Comment by tttp** [comment]
Hi @destag, 

I'm not clear as for when this camelisation happens.

the one that seems to be causing problem is for the graphql subscription to the actionPages changes.

It definitely should not touch at any key into the campaign config or actionpage config. 

I do not understand why the keys are changed to camel case, is this for the graphql schema? is this for the variables available to the mail templates? something else?
