### ISSUE TITLE
reply-to configurable

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#247]
Hi @destag,

for most campaign/organisations, if a target replies to the email, it should go to the initial sender.

however, it should be an option to disable that (for instance if some targets starts abusing the reply to)

Right now, it's hardcoded to remove the reply to, 

https://github.com/fixthestatusquo/proca-server/commit/f66cc7b6457fe7ff0e9d35420930e1e5d3564bea

I'm not sure what's the best way to configure that, it can be either at the campaign or organisation level.

X+

**Comment by tttp** [comment]
Note: it is a change on the database and server, there is no interface yet to toggle that behaviour, just go in the database

if we need to offer it on a regular basis, we would need to expose it into the graphql AND modify the cli to change it

**Comment by destag** [comment]
@tttp I added reply_enabled also to graphql Org schema, so it is possible to change this flag through api. Should I remove this and leave the possibility of modification only through the database?

**Comment by tttp** [comment]
aah, sorry I missed it. no it's fine
