### ISSUE TITLE
Normalize / downcase emails

### ISSUE THREAD

**Issue by marcinkoziej** [fixthestatusquo/proca-server#31]
There was a sync issue with AN becaues of an email starting with caps:

- Foo.bar@gmail.com

I was able too lookup the record by that email, but the record had all lower case letters (foo.bar@gmail.com) so they did not match, which resulted in an error (could not find email to set subscription for).

One obvious solution is to lowercase the emails on personal data creation. However, we cannot always be sure other systems do this (like AN). Still would need to always remember to lowercase all emails.

Another issue is the gmail-ignores-dots thing - to normalize a gmail address, you'd need to remove the dots (foobar@gmail.com), but then it would be impossible to fetch a user record by this email, if they previously created with a dot.
what to do?

**Comment by tttp** [comment]
Well spotted!

technically, I think an email COULD be case sensitive, but in practice, I've never seen it

I think you can lowercase the email coming in.

as for the "." (or +extra), I think that is the user choice, and we shouldn't try to fix it

**Comment by tttp** [comment]
@marcinkoziej , you can close, right?
