### ISSUE TITLE
Replace Bamboo with Swoosh

### ISSUE THREAD

**Issue by marcinkoziej** [fixthestatusquo/proca-server#43]
Situation:

- We are using Bamboo 1.2 (old !!) and BambooMailjet (unmaintained by 2019, we use a fork to support batch send with template/variables)
- We use AwsSES library directly to send batch email (without BambooSES adapter)
- We also fetch template info (name->id mapping) from these services - here we just use HTTP JSON APIs directly

see: `lib/proca/services` for all relevant modules.

We want to:
- Switch to Swoosh wherever Bamboo is used - Swoosh develops all adapters in one project, so adapters are not abandoned. It supports `deliver_many()` by default - and this seems to be supported by adapters.
- Has SMTP, SendInBlue adapters - we want them.
- Maybe use SwooshSes also for AWS SES (not sure if beneficial)

**Comment by hiemanshu** [comment]
Plan for implementation:

1. Refactor email service libraries into `Porca.Service.Email.*` modules -- Refactoring and movies services to specific packages will make the code clearer, and leaving only bare services outside. For example `Proca.Service.EmailBackend` will be a single main module, with all submodules in the `Proca.Service.Email.*` package. In the future this would make it easier to add more service types (SNS, SMS, etc)

2. Replace Bamboo with Swoosh inside the Mailer modules
3. Implement SES using Swoosh
4. Add support for batch sending

**Comment by marcinkoziej** [comment]
The refactor at 1: can you write more what is the goal of this refactor?  The EmailBackend is now already a main file to dispatch methods to particular Mailjet or SES modules. It defines the behaviour they adhere to and main deliver method. Is this just about pushing email related services to a sub-module Proca.Service.Email.Foo? 
How would this help with adding new service types (SNS, SMS is not kind of email).


4. There is already support for batch setting: the EmailBackend.deliver accepts list of EmailRecipient structs which has address + variables to every recipient in batch.

**Comment by hiemanshu** [comment]
The goal of the refactor is to declutter the services modules. Leaving the `EmailBackend` as a main service module, and moving most of the other dependencies into the submodule like `Email.Foo` would mean when we add more dependencies and adapters, we don't have to keep adding them to the services folder until it basically fills up. This will add a structure for future services, and when something like SNS, SMS etc needs to be added the main service `NotificationBackend` `SMSBackend` etc would be in the services folder, with it's depending being in the sub module allowing better and more readable code.


For 4, not all Adapter will support `deliver_many` so it might require some small changes when picking the adapter, and using batch sending. I expect the amount of changes in here to be fairly small.

**Comment by marcinkoziej** [comment]
Ah this is what you had in mind! 
Generally this is a good practice but aren't we over-refactoring here? To give you an idea of what I had in mind for the services included in Proca (and not external micro-services):

1. Most are for email: Mailjet, SendInBlue, SES, SMTP (but I think..not more!)
2. Payment: Stripe, Paypal, not more (no other big player I guess)
3. CRM sync: SQS (other CRMs are so fragmented, I would put CiviCRM, Identity, AN in a microservice - this is already done in @proca/cli tool)
4. SMS Twilio or Plivio (but probably just one not two of them!)
5. Calls  - just one, same as SMS
6. Captcha - Procaptcha 
 
So I think outside of email backends, instead of filling up with modules, Services will fill up with one-submodule modules like SMS.Twilio. Also: We would have to make SMS.Twilio and Calls.Twilio - which might be unnatural way to split these? In the simpler approach we just have a Service.Twilio module that implements behaviours for both calls and smses.

**Comment by marcinkoziej** [comment]
Thinking about this Twilio example more: Perhaps it would be better to have:
- Proca.Service.Twilio that implements SMSBackend and CallBackend behaviours, then to have Service.SMS.Twilio and Service.Call.Twilio, and then duplicate code for eg. API key, error translation
- If Proca.Service.Twilio is too big, we can do submodules Service.Twilio.SMS, Service.Twilio.Call and have them implement SMSBackend and CallBackend, OR we just use Twilio directly until we have an unlikely need to also support Plivio (it seems in OPEN tools that never happened?)
-  For email, i think it would make sense to split out TemplateBackend from EmailBackend - i put the template related methods there, to not over-structurize early, but it makes sense because SMTP does not support any templating. But again, maybe Mailjet.Email and Mailjet.Template would be better structure then Email.Mailjet and Template.Mailjet?
- From the perspective of ownership, the Service is what is primarily owned by the Org (and set up by API key), not the email feature..

**Comment by hiemanshu** [comment]
Yup, makes sense. I'll see what amount of refactor makes sense here, I don't think everything will be required or to be done, but some amount of moving adapters might make sense here. 

Having the `Mailjet` service have everything including templates might make sense, since not all will require them, and it will be a service dependent value. 

OPEN Tools did have some Twilio / Plivo logic that eventually just got moved around to different engines in Rails, etc.

**Comment by marcinkoziej** [comment]
Ok cool, wanted to pass you all the context :)  Proceed with this!

**Comment by hiemanshu** [comment]
Yup, good context! Will be helpful to come back and refer to this to make easy choices :D

**Comment by hiemanshu** [comment]
Closing this since change has been merged
