### ISSUE TITLE
Convert fields table to fields JSON column on actions table

### ISSUE THREAD

**Issue by marcinkoziej** [fixthestatusquo/proca-server#6]
And make following api changes:

- [X] customFields - both action input and output - is Json scalar 
- [X] fields is still supported for input (compatibility) but stored as customFields
- [x] fields is not on output in schema2
- [x] limit the size of fields to 3-5kb **harder then expected to implement**  [Question](https://elixirforum.com/t/any-way-to-limit-an-ecto-map-postgresql-jsonb-size/43405)

**Comment by marcinkoziej** [comment]
Make it max 3-5kb

**Comment by tttp** [comment]
Awesome @marcinkoziej !

**Comment by aaronelliotross** [comment]
Whoo hoo! PostgreSQL JSON is great.

Two questions about limiting the size -

1. Why such a small limit? What if I want to upload base64 inline images or something? I'm not saying that's a good idea - but why not? or a novel? =)
2. For really really big requests that are essentially DOS attacks (by tying up all the works with long reads), maybe let nginx or the web server handle it with a POST size limit?

No strong feelings here - just some thoughts!
