### ISSUE TITLE
add test mode on addAction (or addContactAction)

### ISSUE THREAD

**Issue by tttp** [fixthestatusquo/proca-server#96]
add a new test (boolean) attribute when adding an action. it will have multiple impact on the backend

- if donation, use the test service (eg for stripe)
- do not include in the total count
- do not send to the target (MTT)
for MTT, may be have a "catchall" target for the campaign that will receive them?

# UPDATE 

https://github.com/fixthestatusquo/proca/issues/749

todo:

- [x] - add test boolean to addActionX
- [x] - add test boolean to actions 
- [ ] - remove the live flag
- [ ] - do not add lead consent if test
- [ ] - add test to services
- [x] - use test service with donations
- [ ] - add test bool to action message fmt
- [x] - set processing status to testing if test 
- [x] - respect test in mtt_worker
- [ ] -

**Comment by tttp** [comment]
I don't think we need to tackle everything at once, priorities right now:

- add the test boolean to addActionContact and addAction
- do not send the mtt (or better: send it to the action take with "TEST:" added as a prefix or to the email you're using for preview if easier)

IMO, the rest can be done later

**Comment by marcinkoziej** [comment]
- add test bool to action message fmt - what is this? @tttp

**Comment by tttp** [comment]
no idea anymore @marcinkoziej
